# Generated by Django 4.2.7 on 2025-09-05 01:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('rut', models.CharField(help_text='RUT con formato 12345678-9', max_length=12, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('department', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('face_encoding', models.TextField(blank=True, null=True)),
                ('has_face_registered', models.BooleanField(default=False)),
                ('face_quality_score', models.FloatField(default=0)),
                ('face_registration_date', models.DateTimeField(blank=True, null=True)),
                ('face_variations_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attendance_type', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('location_lat', models.FloatField(blank=True, null=True)),
                ('location_lng', models.FloatField(blank=True, null=True)),
                ('address', models.TextField(blank=True)),
                ('verification_method', models.CharField(choices=[('facial', 'Reconocimiento Facial'), ('qr', 'Código QR'), ('manual', 'Manual/GPS')], default='manual', max_length=10)),
                ('face_confidence', models.FloatField(default=0)),
                ('qr_verified', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('is_offline_sync', models.BooleanField(default=False)),
                ('device_info', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='facial_recognition.employee')),
            ],
            options={
                'verbose_name': 'Registro de Asistencia',
                'verbose_name_plural': 'Registros de Asistencia',
                'ordering': ['-timestamp'],
            },
        ),
    ]
